-- Health tips
INSERT INTO health_tips (category, tip_text) VALUES
                                                 ('Diet & Nutrition', 'Eat a balanced diet rich in fruits, vegetables, lean proteins, and whole grains.'),
                                                 ('Diet & Nutrition', 'Limit processed foods, sugary drinks, and saturated fats.'),
                                                 ('Diet & Nutrition', 'Practice mindful eating: pay attention to your food and hunger cues.'),
                                                 ('Diet & Nutrition', 'Incorporate healthy fats like those from avocados, nuts, and olive oil.'),
                                                 ('Diet & Nutrition', 'Read food labels to make informed choices about what you eat.'),
                                                 ('Diet & Nutrition', 'Plan your meals for the week to ensure a balanced and varied diet.'),
                                                 ('Exercise & Fitness', 'Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity exercise per week.'),
                                                 ('Exercise & Fitness', 'Incorporate strength training exercises at least two days a week.'),
                                                 ('Exercise & Fitness', 'Find an activity you enjoy to make exercise a sustainable habit.'),
                                                 ('Exercise & Fitness', 'Don''t forget to stretch regularly to improve flexibility and prevent injuries.'),
                                                 ('Exercise & Fitness', 'Take short active breaks throughout the day, especially if you have a sedentary job.'),
                                                 ('Mental Wellness', 'Practice mindfulness or meditation for a few minutes each day to reduce stress.'),
                                                 ('Mental Wellness', 'Connect with friends and family regularly to maintain strong social bonds.'),
                                                 ('Mental Wellness', 'Take time for hobbies and activities you enjoy.'),
                                                 ('Mental Wellness', 'Don''t be afraid to seek professional help if you''re struggling with your mental health.'),
                                                 ('Mental Wellness', 'Practice gratitude by regularly noting things you''re thankful for.'),
                                                 ('Sleep Hygiene', 'Aim for 7-9 hours of quality sleep per night.'),
                                                 ('Sleep Hygiene', 'Establish a regular sleep schedule, even on weekends.'),
                                                 ('Sleep Hygiene', 'Create a relaxing bedtime routine to signal your body it''s time to wind down.'),
                                                 ('Sleep Hygiene', 'Avoid screens (phones, TVs, computers) for at least an hour before bed.'),
                                                 ('Hydration', 'Drink plenty of water throughout the day, even if you don''t feel thirsty.'),
                                                 ('Hydration', 'Carry a reusable water bottle as a constant reminder to stay hydrated.'),
                                                 ('General Health', 'Wash your hands frequently to prevent the spread of germs.'),
                                                 ('General Health', 'Schedule regular check-ups with your doctor, even when you feel healthy.'),
                                                 ('General Health', 'Get some sunlight every day for Vitamin D, but remember to use sunscreen.');